name: CI

on:
  pull_request:

jobs:
  qa:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.3', '8.4', '8.5']
        symfony-version: ['6.4.*', '7.*', '8.*']

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug
          tools: composer:v2

      - name: Composer install
        run: composer install --no-interaction --prefer-dist

      - name: Install Symfony matrix dependencies
        run: composer update --no-interaction --prefer-dist --with-all-dependencies symfony/*:${{ matrix.symfony-version }}

      - name: Run PHPUnit
        run: vendor/bin/phpunit -c phpunit.xml.dist  --coverage-text

      - name: Fixture app cache clear
        run: php tests/fixture-app/bin/console cache:clear --env=test --no-interaction

      - name: Fixture app type registry generation
        run: php tests/fixture-app/bin/console flexible_graphql:generate-type-registry --env=test --no-interaction

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse -c phpstan.neon.dist
